import { Product, Category, Order, Customer, OrderStatus, Address } from '../types';
import { INITIAL_PRODUCTS, INITIAL_CATEGORIES, INITIAL_ORDERS, INITIAL_CUSTOMERS } from '../data/mockData';
import { supabase } from '../supabase/client';

const MODE = process.env.NEXT_PUBLIC_DATA_MODE || 'mock';
const isSupabase = MODE === 'supabase';
const STORAGE_KEYS = { PRODUCTS:'dashkirana_products', CATEGORIES:'dashkirana_categories', ORDERS:'dashkirana_orders', CUSTOMERS:'dashkirana_customers' };
const changed = () => { if (typeof window !== 'undefined') window.dispatchEvent(new Event('dashkirana_data_changed')); };

function initializeStorage(){ if(typeof window==='undefined'||isSupabase)return; if(!localStorage.getItem(STORAGE_KEYS.PRODUCTS))localStorage.setItem(STORAGE_KEYS.PRODUCTS,JSON.stringify(INITIAL_PRODUCTS)); if(!localStorage.getItem(STORAGE_KEYS.CATEGORIES))localStorage.setItem(STORAGE_KEYS.CATEGORIES,JSON.stringify(INITIAL_CATEGORIES)); if(!localStorage.getItem(STORAGE_KEYS.ORDERS))localStorage.setItem(STORAGE_KEYS.ORDERS,JSON.stringify(INITIAL_ORDERS)); if(!localStorage.getItem(STORAGE_KEYS.CUSTOMERS))localStorage.setItem(STORAGE_KEYS.CUSTOMERS,JSON.stringify(INITIAL_CUSTOMERS)); }

const mapProduct=(p:any):Product=>({id:p.id,name:p.name,slug:p.slug,categoryId:p.category_id||p.categoryId||'',category:(p.categories?.name||p.category||'Rice & Grains') as Product['category'],description:p.description||'',price:Number(p.price),mrp:Number(p.mrp),discount:p.mrp>p.price?Math.round((1-p.price/p.mrp)*100):0,unit:p.unit,stock:Number(p.stock),image:p.image_url||p.image||'🛒',featured:!!p.featured,active:!!p.active,createdAt:p.created_at||p.createdAt,updatedAt:p.updated_at||p.updatedAt});

export async function getProducts():Promise<Product[]>{ if(isSupabase){const {data,error}=await supabase.from('products').select('*,categories(name)').order('created_at',{ascending:false});if(error)throw error;return (data||[]).map(mapProduct);} initializeStorage();const d=localStorage.getItem(STORAGE_KEYS.PRODUCTS);return d?JSON.parse(d):INITIAL_PRODUCTS; }
export async function getProductById(id:string){const ps=await getProducts();return ps.find(p=>p.id===id)||null;}
export async function searchProducts(q:string,category?:string){let ps=await getProducts();ps=ps.filter(p=>p.active);if(category&&category!=='All')ps=ps.filter(p=>p.category===category);if(q.trim()){const x=q.toLowerCase();ps=ps.filter(p=>p.name.toLowerCase().includes(x)||p.category.toLowerCase().includes(x));}return ps;}

export async function getCategories():Promise<Category[]>{if(isSupabase){const {data,error}=await supabase.from('categories').select('*').eq('active',true).order('sort_order');if(error)throw error;return (data||[]).map(c=>({id:c.id,name:c.name,slug:c.slug,icon:c.icon||'🛒'}));}initializeStorage();const d=localStorage.getItem(STORAGE_KEYS.CATEGORIES);return d?JSON.parse(d):INITIAL_CATEGORIES;}

export async function addProduct(input:Omit<Product,'id'|'createdAt'|'updatedAt'>):Promise<Product>{if(isSupabase){const cats=await getCategories();const c=cats.find(x=>x.name===input.category);const {data,error}=await supabase.from('products').insert({category_id:c?.id||null,name:input.name,slug:input.slug,description:input.description,price:input.price,mrp:input.mrp,stock:input.stock,unit:input.unit,image_url:input.image,featured:input.featured,active:input.active}).select('*,categories(name)').single();if(error)throw error;return mapProduct(data);}const products=await getProducts();const p={...input,id:`prod-${Date.now()}`,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};products.unshift(p);localStorage.setItem(STORAGE_KEYS.PRODUCTS,JSON.stringify(products));changed();return p;}
export async function updateProduct(id:string,updates:Partial<Product>){if(isSupabase){const body:any={};if(updates.name!==undefined)body.name=updates.name;if(updates.slug!==undefined)body.slug=updates.slug;if(updates.description!==undefined)body.description=updates.description;if(updates.price!==undefined)body.price=updates.price;if(updates.mrp!==undefined)body.mrp=updates.mrp;if(updates.stock!==undefined)body.stock=updates.stock;if(updates.unit!==undefined)body.unit=updates.unit;if(updates.image!==undefined)body.image_url=updates.image;if(updates.featured!==undefined)body.featured=updates.featured;if(updates.active!==undefined)body.active=updates.active;if(updates.category!==undefined){const cats=await getCategories();body.category_id=cats.find(c=>c.name===updates.category)?.id||null;}body.updated_at=new Date().toISOString();const {data,error}=await supabase.from('products').update(body).eq('id',id).select('*,categories(name)').single();if(error)throw error;changed();return mapProduct(data);}const products=await getProducts();const i=products.findIndex(p=>p.id===id);if(i<0)return null;products[i]={...products[i],...updates,updatedAt:new Date().toISOString()};localStorage.setItem(STORAGE_KEYS.PRODUCTS,JSON.stringify(products));changed();return products[i];}
export async function updateStock(id:string,stock:number){return updateProduct(id,{stock});}

export async function getOrders():Promise<Order[]>{if(isSupabase){const {data,error}=await supabase.from('orders').select('*,order_items(*),addresses(*)').order('created_at',{ascending:false});if(error)throw error;return (data||[]).map((o:any)=>({id:o.id,customerName:o.customer_name,customerPhone:o.customer_phone,items:(o.order_items||[]).map((i:any)=>({productId:i.product_id,productName:i.product_name,unit:i.unit,price:Number(i.price),quantity:i.quantity,image:i.image||'🛒'})),subtotal:Number(o.subtotal),deliveryFee:Number(o.delivery_fee),total:Number(o.total),address:o.addresses||{},paymentMethod:o.payment_method,status:o.status,createdAt:o.created_at,updatedAt:o.updated_at}));}initializeStorage();const d=localStorage.getItem(STORAGE_KEYS.ORDERS);return d?JSON.parse(d):INITIAL_ORDERS;}
export async function getOrderById(id:string){const os=await getOrders();return os.find(o=>o.id===id)||null;}
export async function createOrder(orderData:Omit<Order,'id'|'createdAt'|'updatedAt'|'status'>):Promise<Order>{if(isSupabase){const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Please sign in before placing an order.');const a=orderData.address as Address;const {data:addr,error:ae}=await supabase.from('addresses').insert({user_id:user.id,name:a.name,phone:a.phone,address_line:a.addressLine,area:a.area,city:a.city,pincode:a.pincode,landmark:a.landmark||'',delivery_instructions:a.deliveryInstructions||''}).select().single();if(ae)throw ae;const {data:o,error:oe}=await supabase.from('orders').insert({user_id:user.id,customer_name:orderData.customerName,customer_phone:orderData.customerPhone,address_id:addr.id,subtotal:orderData.subtotal,delivery_fee:orderData.deliveryFee,total:orderData.total,payment_method:orderData.paymentMethod,status:'Placed'}).select().single();if(oe)throw oe;const {error:ie}=await supabase.from('order_items').insert(orderData.items.map(i=>({order_id:o.id,product_id:i.productId,product_name:i.productName,unit:i.unit,price:i.price,quantity:i.quantity,image:i.image})));if(ie)throw ie;changed();return {...orderData,id:o.id,status:'Placed',createdAt:o.created_at,updatedAt:o.updated_at};}const orders=await getOrders();const o={...orderData,id:`DK${Math.floor(10000+Math.random()*90000)}`,status:'Placed' as OrderStatus,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};orders.unshift(o);localStorage.setItem(STORAGE_KEYS.ORDERS,JSON.stringify(orders));changed();return o;}
export async function updateOrderStatus(id:string,status:OrderStatus){if(isSupabase){const {data,error}=await supabase.from('orders').update({status,updated_at:new Date().toISOString()}).eq('id',id).select().single();if(error)throw error;changed();return getOrderById(data.id);}const orders=await getOrders();const i=orders.findIndex(o=>o.id===id);if(i<0)return null;orders[i].status=status;orders[i].updatedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEYS.ORDERS,JSON.stringify(orders));changed();return orders[i];}

export async function getCustomers():Promise<Customer[]>{if(isSupabase){const {data,error}=await supabase.from('profiles').select('id,full_name,phone,created_at').eq('role','customer').order('created_at',{ascending:false});if(error)throw error;const orders=await getOrders();return (data||[]).map((c:any)=>{const os=orders.filter(o=>o.customerPhone===c.phone);return {id:c.id,name:c.full_name||'Customer',phone:c.phone||'',totalOrders:os.length,totalSpent:os.reduce((s,o)=>s+o.total,0),lastOrderDate:os[0]?.createdAt||c.created_at};});}initializeStorage();const d=localStorage.getItem(STORAGE_KEYS.CUSTOMERS);return d?JSON.parse(d):INITIAL_CUSTOMERS;}
